### ISSUE TITLE
Code compatability with the 'robust fine-tuning ~' paper

### ISSUE THREAD

**Issue by InugYoon** [mlfoundations/patching#2]
Hello, thank you for sharing the great research!

My question is, is this code version easily compatible to the work https://github.com/mlfoundations/wise-ft ??
(since that work is from same research group)
Or, is the overall code structure modified?

Thank you.

**Comment by InugYoon** [comment]
Of course I found a lot similarities between two repos, 
But there seem quite number of modification or structural differencies. 

If I need to ablation on both of them, which one do you recommend to start from?

**Comment by gabrielilharco** [comment]
Hi @InugYoon, thanks for the interest in our work!

This codebase shares many similarities with the [WiSE-FT codebase](https://github.com/mlfoundations/wise-ft), although there are some differences. The most important one is that in this codebase we do not fine-tune the classification heads for each target task, in order to maintain the open-vocabulary nature of the models we fine-tune. The classification heads are initialized using the zero-shot text encoder from CLIP and remain frozen during fine-tuning (see https://github.com/mlfoundations/patching/blob/main/src/heads.py). This codebase also supports more downstream tasks (see https://github.com/mlfoundations/patching/tree/main/src/datasets). Overall, this codebase should be a good starting point, let us know if you run into any issues!

**Comment by InugYoon** [comment]
Thank you for your kind and clear explanations!
Okay, I'll refer to the codes in this repo. 
Thank you for fast reponse!
